### ISSUE TITLE
ngx-quill-upload issue in SSR version (RefrenceError: Node is not defined)

### ISSUE THREAD

**Issue by Malik-shahzadAli** [ayush013/ngx-quill-upload#13]
/home/sb-0/Desktop/seebiz-frontend-v2/dist/seebiz-frontend-v2/server/main.js:360593
var CLIPBOARD_CONFIG = [[Node.TEXT_NODE, matchText], [Node.TEXT_NODE, matchNewline], ['br', matchBreak], [Node.ELEMENT_NODE, matchNewline], [Node.ELEMENT_NODE, matchBlot], [Node.ELEMENT_NODE, matchSpacing], [Node.ELEMENT_NODE, matchAttributor], [Node.ELEMENT_NODE, matchStyles], ['li', matchIndent], ['b', matchAlias.bind(matchAlias, 'bold')], ['i', matchAlias.bind(matchAlias, 'italic')], ['style', matchIgnore]];
                         ^

ReferenceError: Node is not defined
    at Object.defineProperty.value (/home/sb-0/Desktop/seebiz-frontend-v2/dist/seebiz-frontend-v2/server/main.js:360593:26)
    at __webpack_require__ (/home/sb-0/Desktop/seebiz-frontend-v2/dist/seebiz-frontend-v2/server/main.js:351803:30)
    at Object.defineProperty.value (/home/sb-0/Desktop/seebiz-frontend-v2/dist/seebiz-frontend-v2/server/main.js:357385:18)
    at __webpack_require__ (/home/sb-0/Desktop/seebiz-frontend-v2/dist/seebiz-frontend-v2/server/main.js:351803:30)
    at Object.defineProperty.value (/home/sb-0/Desktop/seebiz-frontend-v2/dist/seebiz-frontend-v2/server/main.js:361739:13)
    at __webpack_require__ (/home/sb-0/Desktop/seebiz-frontend-v2/dist/seebiz-frontend-v2/server/main.js:351803:30)
    at Object.<anonymous> (/home/sb-0/Desktop/seebiz-frontend-v2/dist/seebiz-frontend-v2/server/main.js:363251:18)
    at __webpack_require__ (/home/sb-0/Desktop/seebiz-frontend-v2/dist/seebiz-frontend-v2/server/main.js:351803:30)
    at Object.defineProperty.value (/home/sb-0/Desktop/seebiz-frontend-v2/dist/seebiz-frontend-v2/server/main.js:351846:18)
    at /home/sb-0/Desktop/seebiz-frontend-v2/dist/seebiz-frontend-v2/server/main.js:351849:10

![image](https://user-images.githubusercontent.com/57900011/147081548-5562b765-f46b-42a0-ab59-a9bb4b4cb2e9.png)

**Comment by ayush013** [comment]
Won't work as DOM APIs arent present on the server.

https://angular.io/api/platform-browser
Consider adding a custom check to prevent initializing the plugin on the server.
